# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
      - name: Install dependencies
        run: npm ci
      - name: Migrate data
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTE_DATABASE_ID: ${{ secrets.NOTE_DATABASE_ID }}
          TASK_DATABASE_ID: ${{ secrets.TASK_DATABASE_ID }}
        run: npm run-script runcode 
